# Generated by Django 5.2.4 on 2025-08-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idol',
            options={'verbose_name': '아이돌', 'verbose_name_plural': '아이돌'},
        ),
        migrations.AlterModelOptions(
            name='idolmanager',
            options={'verbose_name': '아이돌 매니저', 'verbose_name_plural': '아이돌 매니저'},
        ),
    ]
