# Generated by Django 5.2.4 on 2025-08-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_alter_idol_options_alter_idolmanager_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
