services:
  django:
    image: junhyuk1208/dingding:latest
    container_name: django
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    volumes:
      - static-:/app/staticfiles
      - media-:/app/media
    networks:
      - app_network
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--database", "default"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:7-alpine # 특정 버전 명시
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --port 6379
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: junhyuk1208/dingding_nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      django:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-:/app/staticfiles:ro   # 정적 파일은 읽기 전용(ro)으로 마운트
      - media-:/app/media:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static-:
  media-:
  redis-data:

networks:
  app_network:
    driver: bridge