# Generated by Django 5.2.4 on 2025-08-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="그룹 이름", max_length=100, unique=True
                    ),
                ),
                ("debut_date", models.DateField(help_text="데뷔 일자")),
                ("agency", models.CharField(help_text="소속사", max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "그룹",
                "verbose_name_plural": "그룹들",
            },
        ),
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="시작 시간")),
                ("end_time", models.DateTimeField(help_text="종료 시간")),
                ("location", models.CharField(help_text="장소", max_length=5000)),
                ("description", models.CharField(help_text="설명", max_length=5000)),
                ("is_public", models.BooleanField(default=True, help_text="공개 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "그룹 스케줄",
                "verbose_name_plural": "그룹 스케줄들",
            },
        ),
    ]
