# Generated by Django 5.2.4 on 2025-08-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("debut_date", models.DateField(help_text="데뷔 일자")),
                ("agency", models.CharField(help_text="소속사", max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정 일시"),
                ),
            ],
            options={
                "verbose_name": "그룹",
                "verbose_name_plural": "그룹",
            },
        ),
    ]
