# Generated by Django 5.2.4 on 2025-08-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="logo_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_logos",
                to="users.image",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="그룹 담당 매니저",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
