# Generated by Django 5.2.4 on 2025-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='agency',
            field=models.CharField(help_text='소속사', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='group',
            name='debut_date',
            field=models.DateField(help_text='데뷔 일자'),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo_image_url',
            field=models.URLField(blank=True, help_text='로고 이미지 URL', max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='그룹 이름', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
    ]
