# Generated by Django 5.2.4 on 2025-08-18 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '그룹', 'verbose_name_plural': '그룹'},
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='그룹 담당 매니저', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
