# Generated by Django 5.2.4 on 2025-08-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
    ]
