# Generated by Django 5.2.4 on 2025-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
