# Generated by Django 5.2.4 on 2025-08-07 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idols", "0001_initial"),
        ("users", "0004_image_image_file_alter_image_file_size_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="idolbookmark",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="idolbookmark",
            name="user",
        ),
        migrations.CreateModel(
            name="UserSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "idol_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_added_schedules",
                        to="idols.idolschedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 스케줄",
                "verbose_name_plural": "사용자 스케줄들",
                "db_table": "user_schedules",
                "unique_together": {("user", "idol_schedule")},
            },
        ),
        migrations.DeleteModel(
            name="GroupBookmark",
        ),
        migrations.DeleteModel(
            name="IdolBookmark",
        ),
    ]
