# Generated by Django 5.2.4 on 2025-08-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '그룹 즐겨찾기',
                'verbose_name_plural': '그룹 즐겨찾기들',
                'db_table': 'bookmarks_groupbookmark',
            },
        ),
        migrations.CreateModel(
            name='IdolBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '아이돌 즐겨찾기',
                'verbose_name_plural': '아이돌 즐겨찾기들',
                'db_table': 'bookmarks_idolbookmark',
            },
        ),
    ]
