# Generated by Django 5.2.4 on 2025-08-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookmarks", "0001_initial"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbookmark",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarked_by_users",
                to="groups.group",
            ),
        ),
    ]
