# Generated by Django 5.2.4 on 2025-08-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbookmark',
            options={'verbose_name': '그룹 즐겨찾기', 'verbose_name_plural': '그룹 즐겨찾기'},
        ),
        migrations.AlterModelOptions(
            name='idolbookmark',
            options={'verbose_name': '아이돌 즐겨찾기', 'verbose_name_plural': '아이돌 즐겨찾기'},
        ),
    ]
