# Generated by Django 5.2.4 on 2025-08-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("alarms", "0001_initial"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="group_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="schedules.groupschedule",
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="idol_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="schedules.idolschedule",
            ),
        ),
    ]
