# Generated by Django 5.2.4 on 2025-08-18 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0002_initial"),
        ("idols", "0002_initial"),
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupschedule",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="이 스케줄을 작성한 사용자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_group_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groupschedule",
            name="group",
            field=models.ForeignKey(
                help_text="스케줄이 속한 그룹",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="idolschedule",
            name="idol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="idols.idol",
            ),
        ),
        migrations.AddField(
            model_name="idolschedule",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="이 스케줄을 작성한 아이돌 매니저",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
