# Generated by Django 5.2.4 on 2025-08-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupschedule',
            options={'verbose_name': '그룹 스케줄', 'verbose_name_plural': '그룹 스케줄'},
        ),
        migrations.AlterModelOptions(
            name='idolschedule',
            options={'verbose_name': '아이돌 스케줄', 'verbose_name_plural': '아이돌 스케줄'},
        ),
        migrations.AlterModelOptions(
            name='userschedule',
            options={'verbose_name': '사용자 스케줄', 'verbose_name_plural': '사용자 스케줄'},
        ),
    ]
